"""Triage scan results into grouped PR plans."""
from dataclasses import dataclass, field
from datetime import datetime, timezone


@dataclass
class FileChange:
    """A single file that needs to be changed as part of a PR."""
    path: str
    change_type: str          # "update" | "create"
    description: str
    issues: list[dict] = field(default_factory=list)


@dataclass
class PRPlan:
    """A planned pull request targeting one concern."""
    concern: str              # e.g. "sdk-version-bump"
    branch_name: str
    title: str
    body: str
    file_changes: list[FileChange] = field(default_factory=list)
    priority: int = 0         # lower = higher priority


class PRTriager:
    """Groups scan results into separate PR plans by concern."""

    def triage(self, scan_result: dict) -> list["PRPlan"]:
        """Triage a scan result dict into a sorted list of PRPlans.

        Args:
            scan_result: Output of ScanAnalyzer.scan_module() or equivalent JSON.

        Returns:
            list[PRPlan]: Plans sorted by priority (lowest number first).
        """
        plans: list[PRPlan] = []

        sdk_plan = self._build_sdk_bump_plan(scan_result)
        if sdk_plan:
            plans.append(sdk_plan)

        api_plan = self._build_deprecated_api_plan(scan_result)
        if api_plan:
            plans.append(api_plan)

        plans.sort(key=lambda p: p.priority)
        return plans

    # ------------------------------------------------------------------
    # Internal builders
    # ------------------------------------------------------------------

    @staticmethod
    def _ts() -> str:
        return datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")

    def _build_sdk_bump_plan(self, scan: dict) -> PRPlan | None:
        sdk_info = scan.get("sdk_version_info", {})
        detected = sdk_info.get("detected_version")
        latest = sdk_info.get("latest_recommended")

        # Create a plan if we have version info to work with
        if not detected:
            return None

        ts = self._ts()
        description = f"Bump viam-sdk from {detected}"
        if latest:
            description += f" to {latest}"

        return PRPlan(
            concern="sdk-version-bump",
            branch_name=f"auto/sdk-version-bump-{ts}",
            title=f"chore: bump viam-sdk from {detected}" + (f" to {latest}" if latest else ""),
            body=(
                "## Summary\n"
                f"- Update `viam-sdk` pin in `requirements.txt` from `{detected}`"
                + (f" to `{latest}`" if latest else " to latest")
                + "\n\n"
                "Generated by **viam-module-insights**."
            ),
            file_changes=[
                FileChange(
                    path="requirements.txt",
                    change_type="update",
                    description=description,
                    issues=[{
                        "description": f"SDK pinned at {detected}" + (f", latest is {latest}" if latest else ""),
                        "current_usage": f"viam-sdk=={detected}",
                        "replacement": f"viam-sdk=={latest}" if latest else "viam-sdk>=<latest>",
                    }],
                )
            ],
            priority=0,
        )

    def _build_deprecated_api_plan(self, scan: dict) -> PRPlan | None:
        breaking = scan.get("breaking_changes", [])
        deprecations = scan.get("deprecation_warnings", [])
        all_issues = breaking + deprecations

        if not all_issues:
            return None

        # Group issues by file
        files: dict[str, list[dict]] = {}
        for issue in all_issues:
            path = issue.get("file", "unknown")
            files.setdefault(path, []).append(issue)

        ts = self._ts()
        file_changes = [
            FileChange(
                path=path,
                change_type="update",
                description=f"Fix {len(issues)} deprecated API usage(s)",
                issues=issues,
            )
            for path, issues in files.items()
        ]

        issue_lines = []
        for issue in all_issues:
            line = issue.get("line", "?")
            desc = issue.get("description", "")
            issue_lines.append(f"- `{issue.get('file', '?')}:{line}` — {desc}")
        body_issues = "\n".join(issue_lines)

        return PRPlan(
            concern="migrate-deprecated-apis",
            branch_name=f"auto/migrate-deprecated-apis-{ts}",
            title="fix: migrate deprecated API calls to latest SDK",
            body=(
                "## Summary\n"
                "Replace deprecated API calls flagged by the code scanner.\n\n"
                "### Issues addressed\n"
                f"{body_issues}\n\n"
                "Generated by **viam-module-insights**."
            ),
            file_changes=file_changes,
            priority=1,
        )
